name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Message that will be displayed on users'' first issue'
        pr-message: 'Message that will be displayed on users'' first pr'
- name: https://epg.best/17e4a-cqzhic.xml.gz
  # You may pin to the exact commit or the version.
  # uses: svenstaro/upload-release-action@e74ff71f7d8a4c4745b560a485cc5fdb9b5b999d
  uses: svenstaro/upload-release-action@2.2.0
  with:
    # GitHub token.
    repo_token: 
    # Local file to upload.
    file: 
    # Tag to use as a release.
    tag: 
    # Name of the asset. When not provided will use the file name. Unused if file_glob is set to "true".
    asset_name: # optional
    # Overwrite the release in case it already exists.
    overwrite: # optional
    # If true the file can be a glob pattern, asset_name is ignored if this is true.
    file_glob: # optional
    # Mark the release as a pre-release. Defaults to "false".
    prerelease: # optional
    # Explicitly set a release name. Defaults to empty which will cause the release to take the tag as name on GitHub.
    release_name: # optional
    # Content of the release text. Empty by default.
    body: # optional
    # Specify the name of the GitHub repository in which the GitHub release will be created, edited, and deleted. If the repository is other than the current, it is required to create a personal access token with `repo`, `user`, `admin:repo_hook` scopes to the foreign repository and add it as a secret. Defaults to the current repository
    repo_name: https://github.com/romelp84/iptv
